apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
name: wisecow-zero-trust
namespace: default

spec:
selector:
matchLabels:
app: wisecow

process:
matchPaths:
- path: /usr/bin/bash
- path: /bin/sh

action: Block
